### ISSUE TITLE
图像没对齐吗，检测比原本精度低，而且最后绘制结果也有问题

### ISSUE THREAD

**Issue by futureflsl** [zzzdddyyy/YoloV8Net.Segment#1]
看图，我用的yolov8s-seg.onnx
![result](https://github.com/zzzdddyyy/YoloV8Net.Segment/assets/23259315/af05d785-e46f-4965-9fdc-16c5f2033d62)

**Comment by zzzdddyyy** [comment]
你好，针对此问题，源码已更新。
![image](https://github.com/zzzdddyyy/YoloV8Net.Segment/assets/32119468/ae8fd2ac-a43e-480a-bfef-1512f77dff1a)

**Comment by futureflsl** [comment]
大佬牛x
